title: Welcome!!
description: Yuju's Blog
baseurl: "" # the subpath of your site, e.g. /blog
url: "yuju-00.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Author
author-name:    Yuju
author-image:   1.jpg
author-job:     Software Engineer
author-email:   yooju000326@gmail.com # Add your email for contant form.
author-twitter: artemsheludko_ # Add your twitter account
about-author:   I'm a talking potato.

# Social settings
social-twitter:   
social-facebook:
social-github:    yuju-00
social-pinterest: 
social-instagram: foenrwn
social-youtube:
social-blog:      dbwn_fav  
social-linkedin:

# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1

# Comment Section (Disqus)
disqus-identifier: dbwn # Add your shortname for Disqus Comment. For example mr-brown

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/
plugins:
  - jekyll-paginate

paginate: 7
paginate_path: "/page/:num/"

include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
